### PR TITLE
Project support

### PR DESCRIPTION
**Pull request by kriede**

### CODE REVIEW

**Comment by Zlatkovsky** [comment]
OK, awesome!  Thanks for resolving the comments!

I'm happy to take the pull request... but there is one snag.  Ultimately, we want to make this a project on https://github.com/OfficeDev, and we also want to publish this to the Office Store.  Both should be happening in the reasonably near future.  The problem is that in order to take in your code into MSFT codebase, we need to have you sign some sort of super-simple agreement releasing code ownership.  This agreement is automatically sent out by a bot to anyone who makes a pull request against OfficeDev (or other MSFT-affiliated sites).  But it doesn't when you create a pull request against my personal Github, which is where the project is currently sitting.

So:  we'll need a couple weeks before we can have the OfficeDev-based repo ready, and unfortunately we'll need you to resubmit your pull request again at that time, so that the friendly bot can send you the contribution-agreement.  The process should be painless from there on out.  Does that sound alright?

Thanks again for your enthusiasm, and for being the first to submit a pull request!  I'll get in touch with you once we're ready.

- Michael

**Comment by kriede** [comment]
ok, no problem from my side, I will not claim any rights on my contribution.
Thanx for sending a message once you are ready. I'll then resubmit my pull request to that new repo.

When do you expect the App to be available in the store?
Will the Project support make it into the first release?

**Comment by Zlatkovsky** [comment]
For when the Add-in will be available in the store:  as soon as we can make it.  There are several things we need to do on our side first, both on the technical side (sandbox the snippets, do various UI improvements), legal side (get clearance to ship with the various libraries and services that we're using, create a EULA and privacy policy, etc.), and logistical (create and post to the OfficeDev repo, figure out a hosting place for the add-in, write a readme, etc.).  So I can't commit to a date at this point, simply because I myself don't know!

Re. Project, I need to get "blessings" from the current PM owner for Project to ship the Project support, but I don't see why we wouldn't.  And I think we should be able to make it into the first release:  We should have the repo ready and up before we ship anyway, so at that point if you can submit the changes then, we can just push them in before the release.

**Comment by kriede** [comment]
Yes, I also have realized that UI costumization via Manifest is not supported in Project, what a pitty! I will remove it for the final Pull request to the oncoming new repository.
Can't you ask the PM owner for Project to enable this Feature?

**Comment by Zlatkovsky** [comment]
@kriede, I have passed on the feedback regarding "Add-in Commands" (ribbon customization) to the Project extensibility PM, Heather Heide.

**Comment by Zlatkovsky** [comment]
@kriede , we have moved our repo to OfficeDev, and changed out a huge amount of the code.  In the process, we've also added support for Project, so I don't think this pull request necessarily applies any more... but we'd love to have you dogfood our new playground, and also share some code snippets!

As the project is under NDA for now, could you please email me for further instructions, and I can direct you to the running instructions and repos?  Thanks!

My email is <firstname>.<lastname>@<company-i-work-for>.com

**Pull request closed without merging**
